/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fact_app;
import Datos.reporteTxt;
import Datos.usuarios;
import Datos.usuarios.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frmPrincipal extends javax.swing.JFrame {
    
    //Variables globales
    private usuarios datosUsuarios;
    private int totalIngresos = 0;
    private int totalGastos = 0;


    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();

        // Crear una instancia de la clase 'usuarios'
        datosUsuarios = new usuarios();

        // Obtener nombres de usuarios y establecer el modelo del ComboBox
        String[] nombresProductos = datosUsuarios.obtenerProductos();
        cmbxProductos.setModel(new javax.swing.DefaultComboBoxModel<>(nombresProductos));
        
        //Define la tabla de Ingresos
        DefaultTableModel modeloTabla = new DefaultTableModel();

        tblFactura.setModel(modeloTabla);
        
        //Define la tabla de Gastos
        DefaultTableModel modeloTablaGastos = new DefaultTableModel();

        tblGastos.setModel(modeloTablaGastos);

        // Agrega las columnas necesarias al modelo
        modeloTabla.addColumn("Cliente");
        modeloTabla.addColumn("Correo");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Cantidad");
        modeloTabla.addColumn("Precio Unitario");
        modeloTabla.addColumn("Total con IVA");
        
        // Agrega las columnas necesarias al modelo
        modeloTablaGastos.addColumn("Motivo");
        modeloTablaGastos.addColumn("Monto");
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbxProductos = new javax.swing.JComboBox<>();
        txtPrecioU = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNuevoCliente = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNuevoID = new javax.swing.JTextField();
        btnReestablecer = new javax.swing.JButton();
        lblCorreoNuevo = new javax.swing.JLabel();
        txtCorreoNuevo = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnCierreCaja = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalIngresos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTotalGastos = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTotalGanancias = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblMotivo = new javax.swing.JLabel();
        txtMontoGasto = new javax.swing.JTextField();
        lblMotivo1 = new javax.swing.JLabel();
        txtMotivoGasto = new javax.swing.JTextField();
        btnContabilizarGasto = new javax.swing.JButton();
        btnReestablecerGasto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");

        jLabel3.setText("Cantidad");

        jLabel6.setText("Producto");

        cmbxProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxProductosActionPerformed(evt);
            }
        });

        jLabel7.setText("Cliente");

        txtNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoClienteActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        txtNuevoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoIDActionPerformed(evt);
            }
        });

        btnReestablecer.setText("Reestablecer");
        btnReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReestablecerActionPerformed(evt);
            }
        });

        lblCorreoNuevo.setText("Correo");

        lblTelefono.setText("Telefono");

        jLabel10.setText("Precio");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Factura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnImprimir)
                        .addGap(18, 18, 18)
                        .addComponent(btnReestablecer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblCorreoNuevo)
                            .addComponent(lblTelefono)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad)
                            .addComponent(txtPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevoID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoNuevo)
                    .addComponent(txtCorreoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnReestablecer))
                .addContainerGap())
        );

        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFactura);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        btnCierreCaja.setText("Generar Reporte");
        btnCierreCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierreCajaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Cierre de caja");

        jLabel2.setText("Total Ingresos");

        lblTotalIngresos.setText("000.0");

        jLabel9.setText("Total Ganancias");

        lblTotalGastos.setText("000.0");

        jLabel11.setText("Total Gastos");

        lblTotalGanancias.setText("000.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnCierreCaja)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalGanancias)
                            .addComponent(lblTotalGastos)
                            .addComponent(lblTotalIngresos))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalIngresos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblTotalGastos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblTotalGanancias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnCierreCaja)
                .addGap(28, 28, 28))
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Panel de gastos");

        lblMotivo.setText("Monto");

        txtMontoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoGastoActionPerformed(evt);
            }
        });

        lblMotivo1.setText("Motivo");

        txtMotivoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotivoGastoActionPerformed(evt);
            }
        });

        btnContabilizarGasto.setText("Contabilizar");
        btnContabilizarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContabilizarGastoActionPerformed(evt);
            }
        });

        btnReestablecerGasto.setText("Reestablecer");
        btnReestablecerGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReestablecerGastoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnContabilizarGasto)
                        .addGap(18, 18, 18)
                        .addComponent(btnReestablecerGasto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblMotivo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(txtMotivoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblMotivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMontoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(110, 110, 110))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotivo1)
                    .addComponent(txtMotivoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotivo)
                    .addComponent(txtMontoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReestablecerGasto)
                    .addComponent(btnContabilizarGasto))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblGastos);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Ingresos");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Gastos");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(12, 12, 12))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
     

        // Mostrar un cuadro de diálogo para confirmar la impresión
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea imprimir la factura?",
                "Confirmar impresión",
                JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            // Si el usuario selecciona 'Sí', continuar con la lógica de impresión

            // Obtener los valores seleccionados y escritos
            String nombreUsuario = txtNuevoCliente.getText();
            String correoUsuario = txtCorreoNuevo.getText();
            String telefono = txtTelefono.getText();
            String id = txtNuevoID.getText();
            String producto = cmbxProductos.getSelectedItem().toString();
            String precioU = txtPrecioU.getText();
            String cantidad = txtCantidad.getText();
            int precioUnitario = Integer.parseInt(txtPrecioU.getText());
            int cantidadP = Integer.parseInt(txtCantidad.getText());

            // Llamar al método para agregar un nuevo usuario
            datosUsuarios.agregarNuevoUsuario(nombreUsuario, telefono, id, correoUsuario);

            // Llamar al método para agregar el cálculo
            datosUsuarios.adicionCalculo(nombreUsuario, producto, precioUnitario, cantidadP);

            // Obtener el modelo de la tabla
            DefaultTableModel modeloTabla = (DefaultTableModel) tblFactura.getModel();

            // Obtener los cálculos del usuario
            ArrayList<String> calculos = datosUsuarios.buscarUsuarioPorNombre(nombreUsuario).calculos;

            // Obtener la posición de la última fila en la tabla
            int ultimaFila = modeloTabla.getRowCount();

            // Iterar sobre los cálculos del usuario y agregar las filas a la tabla
            for (String calculo : calculos) {
                // Supongo que los datos están separados por comas o algún carácter
                String[] partes = calculo.split(", ");

                // Agregar una fila con los datos del cálculo
                modeloTabla.addRow(partes);
            }

            // Sumar el total con IVA y actualizar el totalIngresos
            totalIngresos += Double.parseDouble(modeloTabla.getValueAt(ultimaFila, 5).toString());

            // Actualizar el labelTotalIngresos con el total acumulado
            lblTotalIngresos.setText(String.valueOf(totalIngresos));

            // Limpiar los campos después de agregar los cálculos
            txtNuevoCliente.setText("");
            txtCorreoNuevo.setText("");
            txtTelefono.setText("");
            txtNuevoID.setText("");
            txtCantidad.setText("");
            txtPrecioU.setText("");

            int ganancias = totalIngresos - totalGastos;
            lblTotalGanancias.setText(String.valueOf(ganancias));
            // Desplazar la selección a la última fila agregada
            tblFactura.changeSelection(ultimaFila, 0, false, false);
        } else {
            // Si el usuario selecciona 'No' simplemente no hace nada
            System.out.println("El usuario ha cancelado la impresión de la factura.");
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoClienteActionPerformed

    private void btnCierreCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreCajaActionPerformed
        // Obtén los datos de la tabla
        DefaultTableModel modeloTabla = (DefaultTableModel) tblFactura.getModel();
        DefaultTableModel modeloTablaGastos = (DefaultTableModel) tblGastos.getModel();
        int rowCount = modeloTabla.getRowCount();
        ArrayList<String> datosReporte = new ArrayList<>();
        ArrayList<String> datosReporteGastos = new ArrayList<>();

        // Agrega los datos de la tabla a la lista
        for (int i = 0; i < rowCount; i++) {
            String fila = String.format("Cliente: %s, Correo: %s, Producto: %s, Cantidad: %s, Precio Unitario: %s, Total con IVA: %s",
                    modeloTabla.getValueAt(i, 0), modeloTabla.getValueAt(i, 1),
                    modeloTabla.getValueAt(i, 2), modeloTabla.getValueAt(i, 3),
                    modeloTabla.getValueAt(i, 4), modeloTabla.getValueAt(i, 5));
            datosReporte.add(fila);
        }

        // Agrega los datos de la tabla de gastos a la lista
        int rowCountGastos = modeloTablaGastos.getRowCount();
        for (int x = 0; x < rowCountGastos; x++) {
            String filaGasto = String.format("Motivo Gasto: %s, Monto: %s",
                    modeloTablaGastos.getValueAt(x, 0), modeloTablaGastos.getValueAt(x, 1));
            datosReporteGastos.add(filaGasto);
        }

        // Mostrar un cuadro de diálogo para confirmar el cierre de caja
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea realizar el cierre de caja?",
                "Confirmar cierre de caja",
                JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            // Si el usuario selecciona 'Sí', continuar con la lógica de cierre de caja

            // Genera el reporte y lo guarda en un archivo de texto
            reporteTxt.generarReporte(datosReporte, datosReporteGastos, "cierre_caja", lblTotalIngresos.getText(), lblTotalGastos.getText(), lblTotalGanancias.getText());
        } else {
            // Si el usuario selecciona 'No', puedes realizar alguna acción adicional o simplemente salir
            System.out.println("El usuario ha cancelado el cierre de caja.");
        }
    }//GEN-LAST:event_btnCierreCajaActionPerformed

    private void txtNuevoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoIDActionPerformed

    private void btnReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReestablecerActionPerformed
        // Mostrar un cuadro de diálogo para confirmar el restablecimiento
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea restablecer los campos?",
                "Confirmar restablecimiento",
                JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            // Si el usuario selecciona 'Sí', continuar con la lógica de restablecimiento

            // Limpiar los campos después de agregar los cálculos
            txtNuevoCliente.setText("");
            txtCorreoNuevo.setText("");
            txtTelefono.setText("");
            txtNuevoID.setText("");
            txtCantidad.setText("");
            txtPrecioU.setText("");
        } else {
            // Si el usuario selecciona 'No'simplemente salir
            System.out.println("El usuario ha cancelado el restablecimiento de campos.");
        }
    }//GEN-LAST:event_btnReestablecerActionPerformed

    private void cmbxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxProductosActionPerformed
        // Obtiene el producto
        String nombreProducto = cmbxProductos.getSelectedItem().toString();
        
        //Llama a la funcion de obtenerPrecioPorProducto y muestra el precio del producto seleccionado
        String precioU = new usuarios().obtenerPrecioPorProducto(nombreProducto);
        txtPrecioU.setText(precioU);
    }//GEN-LAST:event_cmbxProductosActionPerformed

    private void txtMontoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoGastoActionPerformed

    private void txtMotivoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoGastoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Crear una instancia de frmPrincipal (reemplaza "TuClasePrincipal" con el nombre de tu clase principal)
        frmInicio inicio = new frmInicio();

        // Hacer visible la pantalla principal
        inicio.setVisible(true);

        // Cerrar la ventana actual (opcional, depende de tu lógica de aplicación)
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnContabilizarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContabilizarGastoActionPerformed
        // Obtener los valores seleccionados y escritos
        String motivoGasto = txtMotivoGasto.getText();
        int montoGasto = Integer.parseInt(txtMontoGasto.getText());

        // Mostrar un cuadro de diálogo para confirmar la contabilización del gasto
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Desea contabilizar el gasto?",
            "Confirmar contabilización de gasto",
            JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            // Si el usuario selecciona 'Sí', continuar con la lógica de contabilización del gasto

            // Obtener el modelo de la tabla de gastos
            DefaultTableModel modeloTablaGastos = (DefaultTableModel) tblGastos.getModel();

            // Supongo que los datos están separados por comas o algún carácter
            String[] partes = {motivoGasto, String.valueOf(montoGasto)};

            // Agregar una fila con los datos del gasto
            modeloTablaGastos.addRow(partes);

            // Desplazar la selección a la última fila agregada
            tblGastos.changeSelection(modeloTablaGastos.getRowCount() - 1, 0, false, false);

            // Sumar el monto del gasto y actualizar el totalGastos
            totalGastos += montoGasto;

            // Actualizar el labelTotalGastos con el total acumulado
            lblTotalGastos.setText(String.valueOf(totalGastos));

            // Calcular las ganancias y actualizar el labelTotalGanancias
            double ganancias = totalIngresos - totalGastos;
            lblTotalGanancias.setText(String.valueOf(ganancias));

            // Limpiar los campos después de contabilizar el gasto
            txtMotivoGasto.setText("");
            txtMontoGasto.setText("");
        } else {
            // Si el usuario selecciona 'No' simplemente salir
            System.out.println("El usuario ha cancelado la contabilización del gasto.");
        }
    }//GEN-LAST:event_btnContabilizarGastoActionPerformed

    private void btnReestablecerGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReestablecerGastoActionPerformed
        // Mostrar un cuadro de diálogo para confirmar el restablecimiento de gastos
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea restablecer los campos de gastos?",
                "Confirmar restablecimiento de gastos",
                JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            // Si el usuario selecciona 'Sí', continuar con la lógica de restablecimiento de gastos

            txtMotivoGasto.setText("");
            txtMontoGasto.setText("");
        } else {
            // Si el usuario selecciona 'No'simplemente salir
            System.out.println("El usuario ha cancelado el restablecimiento de campos de gastos.");
        }
    }//GEN-LAST:event_btnReestablecerGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCierreCaja;
    private javax.swing.JButton btnContabilizarGasto;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnReestablecer;
    private javax.swing.JButton btnReestablecerGasto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbxProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCorreoNuevo;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblMotivo1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotalGanancias;
    private javax.swing.JLabel lblTotalGastos;
    private javax.swing.JLabel lblTotalIngresos;
    private javax.swing.JTable tblFactura;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCorreoNuevo;
    private javax.swing.JTextField txtMontoGasto;
    private javax.swing.JTextField txtMotivoGasto;
    private javax.swing.JTextField txtNuevoCliente;
    private javax.swing.JTextField txtNuevoID;
    private javax.swing.JTextField txtPrecioU;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}

